server.port=${PORT:8080}
# 1. Forzamos a Java a hablar MySQL sin preguntar primero
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 2. La URL DEBE empezar exactamente así (revisa el jdbc:mysql://)
spring.datasource.url=jdbc:mysql://bbxzm3hs5wf5noqhcy73-mysql.services.clever-cloud.com:3306/bbxzm3hs5wf5noqhcy73?serverTimezone=UTC

# 3. Credenciales
spring.datasource.username=ufkebbnzhpobkfwa
spring.datasource.password=PzNdRTa91Rg8J5pYNcBr

# 4. Creación automática de la tabla
spring.jpa.hibernate.ddl-auto=update


