spring.datasource.url=jdbc:mysql://blizzq7nymdmt1gskdth-mysql.services.clever-cloud.com:3306/blizzq7nymdmt1gskdth?serverTimezone=UTC
spring.datasource.username=uiysugzarwcpwcjl
spring.datasource.password=T95759936aKYvnfTJkGH
spring.jpa.hibernate.ddl-auto=update
